//------------------------------------------------------------------------------
// <auto-generated>
//     Este código lo generó una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDF_ZOFRATACNA.Formularios.Documentos
{


    public partial class frmDirectorio
    {

        /// <summary>
        /// control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado automáticamente.
        /// Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// Control litUsuario.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUsuario;

        /// <summary>
        /// Control btnLogout.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
    }
}
