//------------------------------------------------------------------------------
// <auto-generated>
//     Este c�digo lo gener� una herramienta.
//
//     Los cambios en este archivo podr�an causar un comportamiento incorrecto y se perder�n si
//     se regenera el c�digo.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDF_ZOFRATACNA.Formularios.Documentos
{


    public partial class frmRegistrarDocumento
    {

        /// <summary>
        /// control form1.
        /// </summary>
        /// <remarks>
        /// Campo generado autom�ticamente.
        /// Para modificarlo, mueva la declaraci�n del campo del archivo del dise�ador al archivo de c�digo subyacente.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// Control litUsuario.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal litUsuario;

        /// <summary>
        /// Control imgAvatar.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgAvatar;

        protected global::System.Web.UI.WebControls.Panel pnlError;
        protected global::System.Web.UI.WebControls.Literal litError;
        protected global::System.Web.UI.WebControls.Panel pnlSuccess;
        protected global::System.Web.UI.WebControls.Literal litSuccess;

        protected global::System.Web.UI.WebControls.TextBox txtAsunto;
        protected global::System.Web.UI.WebControls.DropDownList ddlTipoDoc;
        protected global::System.Web.UI.WebControls.DropDownList ddlAreaResponsable;
        protected global::System.Web.UI.WebControls.TextBox txtFechaEmision;
        protected global::System.Web.UI.WebControls.TextBox txtCodigoReferencia;
        protected global::System.Web.UI.WebControls.TextBox txtDiasMaxRevision;

        protected global::System.Web.UI.WebControls.FileUpload fileUploadPDF;

        protected global::System.Web.UI.WebControls.Repeater rptFirmantes;
        protected global::System.Web.UI.WebControls.DropDownList ddlFirmante;
        protected global::System.Web.UI.WebControls.Button btnAddFirmante;
        protected global::System.Web.UI.WebControls.CustomValidator cvFirmantes;

        protected global::System.Web.UI.WebControls.HyperLink hlCancelar;
        protected global::System.Web.UI.WebControls.Button btnRegistrar;

        /// <summary>
        /// Control btnLogout.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton btnLogout;
    }
}
