//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime: 4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto
//     y se perderán si el código se vuelve a generar.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDF_ZOFRATACNA
{
    public partial class frmLogin
    {
        /// <summary>
        /// Control lblError - Etiqueta para mensajes de error del simulador.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblError;

        /// <summary>
        /// Control cmdAdminUno - Botón de acceso rápido: Administrador 1.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button cmdAdminUno;

        /// <summary>
        /// Control cmdRegistradorUno - Botón de acceso rápido: Registrador 1.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button cmdRegistradorUno;

        /// <summary>
        /// Control cmdRegistradorDos - Botón de acceso rápido: Registrador 2.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button cmdRegistradorDos;

        /// <summary>
        /// Control cmdRegistradorTres - Botón de acceso rápido: Registrador 3.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button cmdRegistradorTres;

        /// <summary>
        /// Control cmdFirmanteUno - Botón de acceso rápido: Firmante 1.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button cmdFirmanteUno;

        /// <summary>
        /// Control cmdFirmanteDos - Botón de acceso rápido: Firmante 2.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button cmdFirmanteDos;

        /// <summary>
        /// Control cmdFirmanteTres - Botón de acceso rápido: Firmante 3.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button cmdFirmanteTres;
    }
}
